uploads = []
generated = []

[[outputs]]
id = "U4kGT9_NV2-ypI1YiE3JX"
uri = "file://MARKLET_project.zip"
type = "unspecified"
title = "MARKLET - كامل الكود المصدري"

[[outputs]]
id = "ytk4Sp2iV0YgnrdWp_y6j"
uri = "file://all_files.txt"
type = "text"
title = "MARKLET - جميع ملفات الكود مدمجة"

[[outputs]]
id = "0SeIhX3uP3LZeMR4u4GEU"
uri = "file://MARKLET_android.zip"
type = "unspecified"
title = "MARKLET Android Project"

[[outputs]]
id = "6H1Ee4cgdNL5CZtISkeUf"
uri = "file://MARKLET_android.tar.gz"
type = "unspecified"
title = "MARKLET Android Project (tar.gz — 7.4MB)"
