import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import carsRouter from "./cars";
import favoritesRouter from "./favorites";
import chatsRouter from "./chats";
import reviewsRouter from "./reviews";
import vehicleReportsRouter from "./vehicleReports";
import aiRouter from "./ai";
import adminRouter from "./admin";
import uploadRouter from "./upload";
import settingsRouter from "./settings";
import promotionsRouter from "./promotions";
import adViewsRouter from "./adViews";
import offersRouter from "./offers";
import buyRequestsRouter from "./buyRequests";
import carPartsRouter from "./carParts";
import junkCarsRouter from "./junkCars";
import rentalCarsRouter from "./rentalCars";
import inspectionsRouter from "./inspections";
import supportMessagesRouter from "./supportMessages";
import missingCarsRouter from "./missingCars";
import notificationsRouter from "./notifications";
import followupRouter from "./followup";
import adsByCategoryRouter from "./adsByCategory";
import feedRouter from "./feed";
import showroomsRouter from "./showrooms";
import videoRouter from "./video";

const router: IRouter = Router();

router.use(adsByCategoryRouter);
router.use(feedRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(carsRouter);
router.use(favoritesRouter);
router.use(chatsRouter);
router.use(reviewsRouter);
router.use(vehicleReportsRouter);
router.use(aiRouter);
router.use(adminRouter);
router.use(uploadRouter);
router.use(settingsRouter);
router.use(promotionsRouter);
router.use(adViewsRouter);
router.use(offersRouter);
router.use(buyRequestsRouter);
router.use(carPartsRouter);
router.use(junkCarsRouter);
router.use(rentalCarsRouter);
router.use(inspectionsRouter);
router.use(supportMessagesRouter);
router.use(missingCarsRouter);
router.use(notificationsRouter);
router.use(followupRouter);
router.use(showroomsRouter);
router.use(videoRouter);

export default router;
