// ─────────────────────────────────────────────────────────────────────────────
// LAZEMNI — نظام التسمية المركزي لعناصر الواجهة
// Central UI naming map for the LAZEMNI car marketplace
// ─────────────────────────────────────────────────────────────────────────────

export const UI = {

  // ─── الصفحات ─────────────────────────────────────────────────────────────
  PAGES: {
    // ── صفحات المستخدم ──
    HOME_01:                      "الصفحة الرئيسية",
    REELS_01:                     "صفحة الفيديوهات",
    REELS_UPLOAD_01:              "رفع فيديو",
    SEARCH_01:                    "البحث",
    CAR_DETAIL_01:                "تفاصيل السيارة",
    POST_01:                      "نشر إعلان",
    VEHICLE_INFO_01:              "معلومات المركبة",
    LOGIN_01:                     "تسجيل الدخول",
    REGISTER_01:                  "إنشاء حساب",
    PROFILE_01:                   "الملف الشخصي",
    CHAT_01:                      "المراسلة",
    FAVORITES_01:                 "المفضلة",
    BUY_REQUESTS_01:              "طلبات الشراء",
    CAR_PARTS_01:                 "قطع السيارات",
    JUNK_CARS_01:                 "سيارات الحوادث",
    MISSING_CARS_01:              "السيارات المسروقة",
    INSPECTIONS_01:               "الفحوصات",
    SUPPORT_01:                   "الدعم والتغذية الراجعة",
    PLATES_01:                    "لوحات السيارات",
    AUCTIONS_01:                  "المزادات",
    RENTAL_CARS_01:               "تأجير السيارات",
    NEW_CARS_01:                  "سيارات جديدة",
    USED_CARS_01:                 "سيارات مستعملة",
    MOTORCYCLES_01:               "الدراجات النارية",
    SHOWROOMS_01:                 "المعارض",
    SHOWROOM_DETAIL_01:           "تفاصيل المعرض",
    SHOWROOM_MANAGE_01:           "إدارة المعرض",
    INSPECTION_CENTERS_01:        "مراكز الفحص",
    INSPECTION_CENTER_DETAIL_01:  "تفاصيل مركز الفحص",
    INSPECTION_CENTER_MANAGE_01:  "إدارة مركز الفحص",
    SCRAP_CENTERS_01:             "مراكز الخردة",
    SCRAP_CENTER_DETAIL_01:       "تفاصيل مركز الخردة",
    SCRAP_CENTER_MANAGE_01:       "إدارة مركز الخردة",
    NOT_FOUND_01:                 "صفحة 404",

    // ── صفحات الادمن ──
    ADMIN_01:                     "لوحة التحكم",
    ADMIN_SYSTEM_AUDIT_01:        "مراجعة النظام",
  },

  // ─── تبويبات الادمن ──────────────────────────────────────────────────────
  ADMIN_TABS: {
    ADMIN_TAB_USERS_01:           "تبويب المستخدمون",
    ADMIN_TAB_DEALERS_01:         "تبويب التجار",
    ADMIN_TAB_SHOWROOMS_01:       "تبويب المعارض",
    ADMIN_TAB_INSPECTION_01:      "تبويب مراكز الفحص",
    ADMIN_TAB_SCRAP_01:           "تبويب مراكز الخردة",
    ADMIN_TAB_REVIEW_01:          "تبويب مراجعة الإعلانات",
    ADMIN_TAB_LISTINGS_01:        "تبويب الإعلانات",
    ADMIN_TAB_INBOX_01:           "تبويب الرسائل الواردة",
    ADMIN_TAB_NOTIFICATIONS_01:   "تبويب الإشعارات",
    ADMIN_TAB_SETTINGS_01:        "تبويب الإعدادات",
  },

  // ─── تبويبات الصفحات ─────────────────────────────────────────────────────
  TABS: {
    TAB_CAR_PARTS_SELL_01:        "تبويب بيع قطعة",
    TAB_CAR_PARTS_BUY_01:         "تبويب طلب قطعة",
    TAB_JUNK_CARS_SELL_01:        "تبويب بيع سيارة حوادث",
    TAB_JUNK_CARS_BUY_01:         "تبويب طلب سيارة حوادث",
    TAB_PLATES_SELL_01:           "تبويب بيع لوحة",
    TAB_PLATES_BUY_01:            "تبويب طلب لوحة",
    TAB_PROFILE_MY_ADS_01:        "تبويب إعلاناتي",
    TAB_PROFILE_OFFERS_01:        "تبويب العروض",
    TAB_PROFILE_INSPECTIONS_01:   "تبويب الفحوصات",
    TAB_SUPPORT_SUPPORT_01:       "تبويب الدعم",
    TAB_SUPPORT_FEEDBACK_01:      "تبويب التغذية الراجعة",
  },

  // ─── الأزرار ─────────────────────────────────────────────────────────────
  BUTTONS: {
    // عام
    BTN_SHARE_01:                 "زر المشاركة",
    BTN_CHAT_01:                  "زر فتح المحادثة",
    BTN_CALL_01:                  "زر الاتصال",
    BTN_WHATSAPP_01:              "زر واتساب",
    BTN_SAVE_01:                  "زر الحفظ في المفضلة",
    BTN_DELETE_01:                "زر الحذف",
    BTN_EDIT_01:                  "زر التعديل",
    BTN_BACK_01:                  "زر الرجوع",
    BTN_NEXT_01:                  "زر التالي",
    BTN_FILTER_01:                "زر الفلترة",
    BTN_SEARCH_01:                "زر البحث",
    BTN_SUBMIT_01:                "زر الإرسال",
    BTN_CANCEL_01:                "زر الإلغاء",
    BTN_UPLOAD_IMAGES_01:         "زر رفع الصور",
    BTN_UPLOAD_VIDEO_01:          "زر رفع الفيديو",
    BTN_PROMOTE_01:               "زر تمييز الإعلان",
    // مستخدم
    BTN_POST_01:                  "زر نشر إعلان جديد",
    BTN_LOGIN_01:                 "زر تسجيل الدخول",
    BTN_REGISTER_01:              "زر إنشاء حساب",
    BTN_LOGOUT_01:                "زر تسجيل الخروج",
    BTN_SOLD_01:                  "زر تأكيد البيع",
    BTN_SELL_LISTING_01:          "زر فتح نموذج البيع",
    BTN_BUY_LISTING_01:           "زر فتح نموذج الشراء",
    BTN_FOUND_01:                 "زر تأكيد العثور على السيارة",
    BTN_SEND_MSG_01:              "زر إرسال رسالة",
    BTN_SEND_AUDIO_01:            "زر إرسال رسالة صوتية",
    BTN_SEND_SUPPORT_01:          "زر إرسال طلب دعم",
    BTN_SEND_FEEDBACK_01:         "زر إرسال تغذية راجعة",
    BTN_INSPECT_REQUEST_01:       "زر طلب فحص",
    BTN_VEHICLE_REPORT_01:        "زر فحص تاريخ المركبة",
    BTN_REELS_UPLOAD_01:          "زر رفع فيديو",
    // ادمن
    BTN_ADMIN_APPROVE_01:         "زر الموافقة (ادمن)",
    BTN_ADMIN_REJECT_01:          "زر الرفض (ادمن)",
    BTN_ADMIN_DELETE_01:          "زر الحذف (ادمن)",
    BTN_ADMIN_FEATURE_01:         "زر التمييز (ادمن)",
    BTN_ADMIN_BAN_01:             "زر الحظر (ادمن)",
    BTN_ADMIN_PROMOTE_DEALER_01:  "زر ترقية تاجر (ادمن)",
    BTN_BROADCAST_SEND_01:        "زر إرسال إشعار جماعي",
    BTN_ADMIN_REFRESH_01:         "زر تحديث البيانات (ادمن)",
    BTN_ADMIN_EXPORT_01:          "زر تصدير البيانات (ادمن)",
    BTN_ADMIN_OPEN_CHAT_01:       "زر فتح محادثة المستخدم (ادمن)",
  },

  // ─── النماذج ─────────────────────────────────────────────────────────────
  FORMS: {
    FORM_POST_01:                    "فورم نشر الإعلان",
    FORM_LOGIN_01:                   "فورم تسجيل الدخول",
    FORM_REGISTER_01:                "فورم إنشاء حساب",
    FORM_CHAT_01:                    "فورم إرسال رسالة",
    FORM_SUPPORT_01:                 "فورم الدعم",
    FORM_FEEDBACK_01:                "فورم التغذية الراجعة",
    FORM_BUY_REQUEST_01:             "فورم طلب الشراء",
    FORM_SELL_PART_01:               "فورم بيع قطعة سيارة",
    FORM_BUY_PART_01:                "فورم طلب قطعة سيارة",
    FORM_SELL_JUNK_01:               "فورم بيع سيارة حوادث",
    FORM_BUY_JUNK_01:                "فورم طلب سيارة حوادث",
    FORM_SELL_PLATE_01:              "فورم بيع لوحة",
    FORM_BUY_PLATE_01:               "فورم طلب لوحة",
    FORM_MISSING_CAR_01:             "فورم إبلاغ سيارة مسروقة",
    FORM_SHOWROOM_MANAGE_01:         "فورم إدارة المعرض",
    FORM_INSPECTION_CENTER_MANAGE_01:"فورم إدارة مركز الفحص",
    FORM_SCRAP_CENTER_MANAGE_01:     "فورم إدارة مركز الخردة",
    FORM_BROADCAST_01:               "فورم الإشعار الجماعي",
    FORM_ADMIN_SHOWROOM_EDIT_01:     "فورم تعديل معرض (ادمن)",
    FORM_VEHICLE_INFO_01:            "فورم استعلام معلومات المركبة",
    FORM_REELS_UPLOAD_01:            "فورم رفع فيديو",
  },

  // ─── حقول الإدخال ────────────────────────────────────────────────────────
  INPUTS: {
    INPUT_TITLE_01:            "عنوان الإعلان",
    INPUT_PRICE_01:            "السعر",
    INPUT_DESCRIPTION_01:      "الوصف",
    INPUT_PHONE_01:            "رقم الهاتف",
    INPUT_EMAIL_01:            "البريد الإلكتروني",
    INPUT_PASSWORD_01:         "كلمة المرور",
    INPUT_IMAGES_01:           "رفع الصور",
    INPUT_VIDEO_01:            "رفع الفيديو",
    INPUT_SEARCH_01:           "مربع البحث",
    INPUT_CHAT_MESSAGE_01:     "مربع رسالة الدردشة",
    INPUT_YEAR_01:             "سنة الصنع",
    INPUT_MILEAGE_01:          "الكيلومتراج",
    INPUT_BRAND_01:            "الماركة",
    INPUT_MODEL_01:            "الموديل",
    INPUT_CITY_01:             "المدينة",
    INPUT_DEALER_01:           "اسم المعرض",
    INPUT_COLOR_01:            "اللون",
    INPUT_FUEL_01:             "نوع الوقود",
    INPUT_TRANSMISSION_01:     "ناقل الحركة",
    INPUT_VIN_01:              "رقم الشاسيه (VIN)",
    INPUT_PLATE_NUMBER_01:     "رقم اللوحة",
    INPUT_PART_NAME_01:        "اسم القطعة",
    INPUT_BROADCAST_TITLE_01:  "عنوان الإشعار الجماعي",
    INPUT_BROADCAST_BODY_01:   "نص الإشعار الجماعي",
    INPUT_ADMIN_SEARCH_01:     "مربع بحث (ادمن)",
    INPUT_SUPPORT_MSG_01:      "نص رسالة الدعم",
    INPUT_FEEDBACK_MSG_01:     "نص التغذية الراجعة",
    INPUT_MISSING_CAR_DESC_01: "وصف السيارة المسروقة",
    INPUT_REELS_TITLE_01:      "عنوان الفيديو",
    INPUT_REELS_VIDEO_01:      "ملف الفيديو",
    INPUT_INSPECTION_NOTES_01: "ملاحظات طلب الفحص",
  },

  // ─── النوافذ المنبثقة ─────────────────────────────────────────────────────
  MODALS: {
    // مستخدم
    MODAL_SHARE_01:              "نافذة المشاركة",
    MODAL_FILTER_01:             "نافذة الفلترة",
    MODAL_BUY_REQUEST_DETAIL_01: "نافذة تفاصيل طلب الشراء",
    MODAL_MISSING_CAR_INFO_01:   "نافذة إرسال معلومات سيارة مسروقة",
    MODAL_CAR_SOLD_CONFIRM_01:   "نافذة تأكيد البيع",
    MODAL_CAR_EDIT_WARNING_01:   "نافذة تنبيه قبل التعديل",
    MODAL_CAR_EDIT_01:           "نافذة تعديل الإعلان",
    MODAL_LISTING_DETAIL_01:     "نافذة تفاصيل الإعلان (ListingDetailDialog)",
    MODAL_LISTING_PREVIEW_01:    "نافذة معاينة الإعلان (ListingPreviewDialog)",
    MODAL_FEATURE_AD_01:         "نافذة تمييز الإعلان",
    MODAL_RATING_01:             "نافذة تقييم التطبيق",
    MODAL_SELL_PART_01:          "نافذة بيع قطعة سيارة",
    MODAL_BUY_PART_01:           "نافذة طلب قطعة سيارة",
    MODAL_SELL_JUNK_01:          "نافذة بيع سيارة حوادث",
    MODAL_BUY_JUNK_01:           "نافذة طلب سيارة حوادث",
    MODAL_SELL_PLATE_01:         "نافذة بيع لوحة",
    MODAL_BUY_PLATE_01:          "نافذة طلب لوحة",
    MODAL_SELL_RENTAL_01:        "نافذة تأجير سيارة",
    MODAL_AUCTION_01:            "نافذة تفاصيل المزاد",
    // ادمن
    MODAL_ADMIN_VIDEO_PREVIEW_01:"نافذة معاينة الفيديو (ادمن)",
    MODAL_ADMIN_BROADCAST_01:    "نافذة إرسال إشعار جماعي",
    MODAL_ADMIN_SHOWROOM_EDIT_01:"نافذة تعديل/إضافة معرض (ادمن)",
    MODAL_ADMIN_CAR_DETAIL_01:   "نافذة تفاصيل إعلان (ادمن)",
  },

  // ─── المكونات ─────────────────────────────────────────────────────────────
  COMPONENTS: {
    COMP_HEADER_01:              "الترويسة",
    COMP_BOTTOM_NAV_01:          "شريط التنقل السفلي",
    COMP_CARD_CAR_01:            "بطاقة السيارة",
    COMP_CARD_LISTING_01:        "بطاقة الإعلان (ListingCard)",
    COMP_CARD_BUY_REQUEST_01:    "بطاقة طلب الشراء",
    COMP_SHARE_SHEET_01:         "ورقة المشاركة",
    COMP_CONTACT_BUTTONS_01:     "أزرار التواصل (اتصال / واتساب / محادثة)",
    COMP_DHIKR_BAR_01:           "شريط الذكر",
    COMP_TOP_BANNER_01:          "البانر الإعلاني العلوي",
    COMP_VIDEO_CAROUSEL_01:      "كاروسيل الفيديو",
    COMP_SAVE_BUTTON_01:         "زر الحفظ في المفضلة",
    COMP_VEHICLE_REPORT_01:      "ودجة تقرير المركبة",
    COMP_APP_RATING_POPUP_01:    "نافذة تقييم التطبيق",
    COMP_PULL_TO_REFRESH_01:     "السحب للتحديث",
    COMP_PAGE_WRAPPER_01:        "غلاف الصفحة",
    COMP_TOP_BANNER_DHIKR_01:    "بانر الذكر العلوي",
  },

  // ─── واجهات برمجة التطبيقات ───────────────────────────────────────────────
  APIS: {
    // مصادقة
    API_AUTH_LOGIN_01:            "POST /auth/login",
    API_AUTH_REGISTER_01:         "POST /auth/register",
    API_AUTH_ME_01:               "GET /auth/me",
    // سيارات
    API_CARS_LIST_01:             "GET /cars",
    API_CARS_DETAIL_01:           "GET /cars/:id",
    API_CARS_CREATE_01:           "POST /cars/create",
    API_CARS_UPDATE_01:           "PATCH /cars/:id",
    API_CARS_DELETE_01:           "DELETE /cars/:id",
    API_CARS_SOLD_01:             "POST /cars/:id/sold",
    API_CARS_FEATURED_01:         "GET /cars/featured",
    API_CARS_SIMILAR_01:          "GET /cars/:id/similar",
    API_CARS_PROMOTE_01:          "POST /cars/:id/promote",
    API_CARS_IMAGES_01:           "POST /cars/:id/images",
    // خلاصة
    API_FEED_01:                  "GET /feed",
    API_SEARCH_01:                "GET /search",
    // محادثات
    API_CHATS_LIST_01:            "GET /chats",
    API_CHATS_START_01:           "POST /chats/start",
    API_CHATS_MESSAGES_01:        "GET /chats/:id/messages",
    API_CHATS_SEND_01:            "POST /chats/:id/messages",
    API_CHATS_SEND_IMAGE_01:      "POST /chats/:id/messages/image",
    API_CHATS_SEND_AUDIO_01:      "POST /chats/:id/messages/audio",
    API_CHATS_BLOCK_01:           "POST /chats/:id/block",
    // مستخدمون
    API_USERS_PROFILE_01:         "GET /profile",
    API_USERS_UPDATE_01:          "PATCH /users/:id",
    API_USERS_AVATAR_01:          "POST /users/:id/avatar",
    // مفضلة
    API_FAVORITES_LIST_01:        "GET /favorites",
    API_FAVORITES_ADD_01:         "POST /favorites",
    API_FAVORITES_DELETE_01:      "DELETE /favorites/:carId",
    // طلبات الشراء
    API_BUY_REQUESTS_LIST_01:     "GET /buy-requests",
    API_BUY_REQUESTS_MINE_01:     "GET /buy-requests/mine",
    API_BUY_REQUESTS_CREATE_01:   "POST /buy-requests",
    API_BUY_REQUESTS_DELETE_01:   "DELETE /buy-requests/:id",
    // قطع السيارات
    API_CAR_PARTS_LIST_01:        "GET /car-parts",
    API_CAR_PARTS_CREATE_01:      "POST /car-parts",
    API_CAR_PARTS_DELETE_01:      "DELETE /car-parts/:id",
    // سيارات الحوادث
    API_JUNK_CARS_LIST_01:        "GET /junk-cars",
    API_JUNK_CARS_CREATE_01:      "POST /junk-cars",
    API_JUNK_CARS_DELETE_01:      "DELETE /junk-cars/:id",
    // سيارات التأجير
    API_RENTAL_CARS_LIST_01:      "GET /rental-cars",
    API_RENTAL_CARS_CREATE_01:    "POST /rental-cars",
    API_RENTAL_CARS_DELETE_01:    "DELETE /rental-cars/:id",
    // السيارات المسروقة
    API_MISSING_CARS_LIST_01:     "GET /missing-cars",
    API_MISSING_CARS_CREATE_01:   "POST /missing-cars",
    API_MISSING_CARS_FOUND_01:    "PATCH /missing-cars/:id/found",
    API_MISSING_CARS_DELETE_01:   "DELETE /missing-cars/:id",
    // لوحات السيارات
    API_SAVES_LIST_01:            "GET /saves",
    API_SAVES_IDS_01:             "GET /saves/ids",
    API_SAVES_ADD_01:             "POST /saves",
    API_SAVES_DELETE_01:          "DELETE /saves/:type/:id",
    // إشعارات
    API_NOTIFICATIONS_LIST_01:    "GET /notifications",
    API_NOTIFICATIONS_READ_01:    "PATCH /notifications/:id/read",
    API_NOTIFICATIONS_READ_ALL_01:"POST /notifications/read-all",
    // إشعارات Push
    API_PUSH_SUBSCRIBE_01:        "POST /push/subscribe",
    API_PUSH_FCM_TOKEN_01:        "POST /push/fcm-token",
    API_PUSH_BROADCAST_01:        "POST /push/broadcast",
    API_PUSH_TEST_01:             "POST /push/test",
    // معارض
    API_SHOWROOMS_LIST_01:        "GET /showrooms",
    API_SHOWROOMS_DETAIL_01:      "GET /showrooms/:id",
    API_SHOWROOMS_MY_01:          "GET /showrooms/my",
    API_SHOWROOMS_UPDATE_01:      "PATCH /showrooms/my",
    // مراكز الفحص
    API_INSPECTION_CENTERS_LIST_01:   "GET /inspection-centers",
    API_INSPECTION_CENTERS_DETAIL_01: "GET /inspection-centers/:id",
    API_INSPECTION_CENTERS_MY_01:     "GET /inspection-centers/my",
    API_INSPECTIONS_MINE_01:          "GET /inspections/mine",
    // مراكز الخردة
    API_SCRAP_CENTERS_LIST_01:    "GET /scrap-centers",
    API_SCRAP_CENTERS_DETAIL_01:  "GET /scrap-centers/:id",
    API_SCRAP_CENTERS_MY_01:      "GET /scrap-centers/my",
    // دعم
    API_SUPPORT_01:               "POST /support",
    API_FEEDBACK_01:              "POST /feedback",
    // ذكاء اصطناعي
    API_AI_DESCRIPTION_01:        "POST /ai/generate-description",
    API_AI_PRICE_01:              "POST /ai/estimate-price",
    API_AI_RECOMMENDATIONS_01:    "GET /ai/recommendations",
    // تقرير المركبة
    API_VEHICLE_REPORT_01:        "POST /vehicle-reports/lookup",
    // ريلز
    API_REELS_LIST_01:            "GET /reels",
    API_REELS_UPLOAD_01:          "POST /reels/upload",
    API_REELS_VIEW_01:            "POST /reels/:id/view",
    API_REELS_LIKE_01:            "POST /reels/:id/like",
    // ادمن
    API_ADMIN_DASHBOARD_01:       "GET /admin/dashboard",
    API_ADMIN_USERS_01:           "GET /admin/users",
    API_ADMIN_CARS_01:            "GET /admin/cars",
    API_ADMIN_PENDING_CARS_01:    "GET /admin/pending-cars",
    API_ADMIN_APPROVE_01:         "POST /admin/approve/:id",
    API_ADMIN_CAR_STATUS_01:      "PATCH /admin/cars/:id/status",
    API_ADMIN_CAR_FEATURE_01:     "PATCH /admin/cars/:id/feature",
    API_ADMIN_SHOWROOMS_01:       "GET /admin/showrooms",
    API_ADMIN_SETTINGS_01:        "GET /admin/settings",
    API_ADMIN_SYSTEM_AUDIT_01:    "GET /admin/system-audit",
    API_ADMIN_STATS_01:           "GET /admin/stats",
    API_ADMIN_CONVERSATIONS_01:   "GET /admin/conversations",
    API_ADMIN_REELS_01:           "GET /admin/reels",
    API_ADMIN_REELS_APPROVE_01:   "PATCH /admin/reels/:id/approve",
  },

  // ─── التوجيه ──────────────────────────────────────────────────────────────
  ROUTES: {
    "/":                         "HOME_01",
    "/reels":                    "REELS_01",
    "/reels/upload":             "REELS_UPLOAD_01",
    "/search":                   "SEARCH_01",
    "/cars/:id":                 "CAR_DETAIL_01",
    "/add-listing":              "POST_01",
    "/vehicle-info":             "VEHICLE_INFO_01",
    "/login":                    "LOGIN_01",
    "/register":                 "REGISTER_01",
    "/profile":                  "PROFILE_01",
    "/chat":                     "CHAT_01",
    "/messages":                 "CHAT_01",
    "/favorites":                "FAVORITES_01",
    "/buy-requests":             "BUY_REQUESTS_01",
    "/car-parts":                "CAR_PARTS_01",
    "/junk-cars":                "JUNK_CARS_01",
    "/missing-cars":             "MISSING_CARS_01",
    "/inspections":              "INSPECTIONS_01",
    "/support":                  "SUPPORT_01",
    "/plates":                   "PLATES_01",
    "/auctions":                 "AUCTIONS_01",
    "/rental-cars":              "RENTAL_CARS_01",
    "/new-cars":                 "NEW_CARS_01",
    "/used-cars":                "USED_CARS_01",
    "/motorcycles":              "MOTORCYCLES_01",
    "/showrooms":                "SHOWROOMS_01",
    "/showroom/:id":             "SHOWROOM_DETAIL_01",
    "/showroom/manage":          "SHOWROOM_MANAGE_01",
    "/inspection-centers":       "INSPECTION_CENTERS_01",
    "/inspection-center/:id":    "INSPECTION_CENTER_DETAIL_01",
    "/inspection-center/manage": "INSPECTION_CENTER_MANAGE_01",
    "/scrap-centers":            "SCRAP_CENTERS_01",
    "/scrap-center/:id":         "SCRAP_CENTER_DETAIL_01",
    "/scrap-center/manage":      "SCRAP_CENTER_MANAGE_01",
    "/admin":                    "ADMIN_01",
    "/admin/system-audit":       "ADMIN_SYSTEM_AUDIT_01",
  },
} as const;

export type UICode = keyof typeof UI.PAGES
  | keyof typeof UI.ADMIN_TABS
  | keyof typeof UI.TABS
  | keyof typeof UI.BUTTONS
  | keyof typeof UI.FORMS
  | keyof typeof UI.INPUTS
  | keyof typeof UI.MODALS
  | keyof typeof UI.COMPONENTS
  | keyof typeof UI.APIS;
