// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-themes/Current.tsx": () => import("../components/mockups/color-themes/Current.tsx"),
  "./components/mockups/color-themes/SilverSlate.tsx": () => import("../components/mockups/color-themes/SilverSlate.tsx"),
  "./components/mockups/color-themes/TealAmber.tsx": () => import("../components/mockups/color-themes/TealAmber.tsx")
};
